/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author yunitarp2706
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    public JButton getLogin() {
        return Login;
    }

    public JTextField getUsenameLogIn() {
        return UsenameLogIn;
    }

    public JPasswordField getPasswordLogIn() {
        return PasswordLogIn;
    }
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dasar = new javax.swing.JPanel();
        HalamanUtama = new javax.swing.JPanel();
        btnSignUp = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        HalamanLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        UsenameLogIn = new javax.swing.JTextField();
        Login = new javax.swing.JButton();
        PasswordLogIn = new javax.swing.JPasswordField();
        LoginBack = new javax.swing.JButton();
        SignUp = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        SignUpDosen = new javax.swing.JButton();
        SignUpMahasiswa = new javax.swing.JButton();
        BackSignUp = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dasar.setLayout(new java.awt.CardLayout());

        btnSignUp.setText("Sign Up");

        btnLogin.setText("Login");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("SELAMAT DATANG");

        jLabel3.setText("Di Sistem Informasi Tugas Akhir");

        jLabel4.setText("Silahkan pilih menu di bawah ini");

        javax.swing.GroupLayout HalamanUtamaLayout = new javax.swing.GroupLayout(HalamanUtama);
        HalamanUtama.setLayout(HalamanUtamaLayout);
        HalamanUtamaLayout.setHorizontalGroup(
            HalamanUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HalamanUtamaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(HalamanUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(HalamanUtamaLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(btnLogin)
                .addGap(87, 87, 87)
                .addComponent(btnSignUp)
                .addContainerGap(214, Short.MAX_VALUE))
        );
        HalamanUtamaLayout.setVerticalGroup(
            HalamanUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HalamanUtamaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(42, 42, 42)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(HalamanUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSignUp)
                    .addComponent(btnLogin))
                .addGap(238, 238, 238))
        );

        dasar.add(HalamanUtama, "HalamanUtama");

        jLabel1.setText("Login");

        jLabel6.setText("Username");

        jLabel7.setText("Password");

        Login.setText("Login");

        LoginBack.setText("Back");

        javax.swing.GroupLayout HalamanLoginLayout = new javax.swing.GroupLayout(HalamanLogin);
        HalamanLogin.setLayout(HalamanLoginLayout);
        HalamanLoginLayout.setHorizontalGroup(
            HalamanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HalamanLoginLayout.createSequentialGroup()
                .addGroup(HalamanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HalamanLoginLayout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabel1))
                    .addGroup(HalamanLoginLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(HalamanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(HalamanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PasswordLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(UsenameLogIn)))
                    .addGroup(HalamanLoginLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(Login)
                        .addGap(51, 51, 51)
                        .addComponent(LoginBack)))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        HalamanLoginLayout.setVerticalGroup(
            HalamanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HalamanLoginLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(HalamanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(UsenameLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HalamanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(PasswordLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(HalamanLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login)
                    .addComponent(LoginBack))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        dasar.add(HalamanLogin, "HalamanLogin");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Pilih Jenis Sign Up");

        SignUpDosen.setText("1. Dosen");
        SignUpDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpDosenActionPerformed(evt);
            }
        });

        SignUpMahasiswa.setText("2. Mahasiswa");

        BackSignUp.setText("3.Back");

        javax.swing.GroupLayout SignUpLayout = new javax.swing.GroupLayout(SignUp);
        SignUp.setLayout(SignUpLayout);
        SignUpLayout.setHorizontalGroup(
            SignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpLayout.createSequentialGroup()
                .addGroup(SignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SignUpLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel5))
                    .addGroup(SignUpLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addGroup(SignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SignUpMahasiswa)
                            .addComponent(SignUpDosen)
                            .addComponent(BackSignUp))))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        SignUpLayout.setVerticalGroup(
            SignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SignUpLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel5)
                .addGap(39, 39, 39)
                .addComponent(SignUpDosen)
                .addGap(40, 40, 40)
                .addComponent(SignUpMahasiswa)
                .addGap(50, 50, 50)
                .addComponent(BackSignUp)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        dasar.add(SignUp, "SignUp");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        dasar.add(jPanel1, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dasar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dasar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignUpDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpDosenActionPerformed

    /**
     * @param args the command line arguments
     */

    public JButton getBtnSignUp() {
        return btnSignUp;
    }
    
    public void showMessage(String pesan) {
        JOptionPane.showMessageDialog(null, pesan);
    }
    
    public void showMessage(String pesan, String judul, int jenisMessage) {
        JOptionPane.showMessageDialog(null, pesan, judul, jenisMessage);
    }

    public JButton getBtnLogin() {
        return btnLogin;
    }

    public JPanel getDasar() {
        return dasar;
    }

    public JButton getLoginBack() {
        return LoginBack;
    }
   
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackSignUp;
    private javax.swing.JPanel HalamanLogin;
    private javax.swing.JPanel HalamanUtama;
    private javax.swing.JButton Login;
    private javax.swing.JButton LoginBack;
    private javax.swing.JPasswordField PasswordLogIn;
    private javax.swing.JPanel SignUp;
    private javax.swing.JButton SignUpDosen;
    private javax.swing.JButton SignUpMahasiswa;
    private javax.swing.JTextField UsenameLogIn;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JPanel dasar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
